### ISSUE TITLE
Build event commands should not use hard-coded paths

### ISSUE THREAD

**Issue by CaioProiete** [Excel-DNA/ExcelDna#16]
They should use macros to determine the path based on the project (or solution path).

![build-event](https://cloud.githubusercontent.com/assets/177608/9545156/4f7092da-4d5d-11e5-8fe7-2915580c835c.png)

This would enhance the experience of developing an Excel add-in with a team or developing an open-source add-in, as any person would be able to clone the repository and compile the project, no matter what folder structure they used.

**Comment by govert** [comment]
I think this is already fixed. Can you check again with a new project and adding the pre-release NuGet package:
    
    > Install-Package -Pre ExcelDna.AddIn

There is one place where the path is hard-coded, and that is in the Debug command line. I am not sure how to set the working directory to be the Output folder, and I thought Excel would sometimes use the wrong directory. So I added the full path there. But now I'm not sure whether that is needed, or how to find out. One user had ".\" as the Working Directory, but is that different to the default?

**Comment by CaioProiete** [comment]
Thanks @govert.

I've just tested with `v0.33.7-rc1` from the NuGet feed and it is not fixed there, at least.
![build-event-2](https://cloud.githubusercontent.com/assets/177608/9558105/3c23dc90-4db8-11e5-98ff-22e5c29d87d2.png)

Regarding the Debug, what I've found is that when you ask Visual Studio to debug an application, it automatically sets the working directory to `bin\Debug` (or `bin\Release` depending on the build config selected), so if you just put the name of the XLL file without any path, it just works.

Here is a screenshot of how I configure all my add-ins:

![start-program](https://cloud.githubusercontent.com/assets/177608/9558167/cd612410-4db8-11e5-94d1-3408720ea770.png)

**Comment by govert** [comment]
OK, so I create a new Class Library project, and then do 
`PM> Install-Package -Pre ExcelDna.Addin`

Then I get:
![image](https://cloud.githubusercontent.com/assets/414659/9558265/dbb748a2-4de3-11e5-8198-dc7f6dd525e4.png)

What are you doing?

**Comment by interdrift** [comment]
This is indeed something that would be very useful. I had a colleague of mine download my code and it turned out he couldn't compile it until he uninstalls excel-dna package and download it again from nuget.

**Comment by govert** [comment]
@CaioProiete I've looked at the code for the Install.ps1 here: https://github.com/Excel-DNA/ExcelDna/blob/master/Package/ExcelDna.AddIn/tools/install.ps1

I do a substitution of the path with `$(ProjectDir)` if it's correct. Maybe you're installing the package into the `$(SolutionDir)` and we need to add some logic to check for that case too. What variable would correspond to your path?

**Comment by CaioProiete** [comment]
(I replied to this post before, but for some reason it is not showing up anymore, so will post again)

---

@govert: I'm not doing anything special... Simple vanilla Class Library, with File => New Project, typing a name, then installing the pre-release NuGet package. And yet, I get the hard-coded paths every time:

![build-events](https://cloud.githubusercontent.com/assets/177608/9559610/7283d290-4dcc-11e5-9f05-fad28a494d13.png)

Tried different computers... Same result.

I believe I'm downloading the right package. This is the NuGet's log:
```
PM> Install-Package -Pre ExcelDna.Addin
Attempting to resolve dependency 'ExcelDna.Integration (≥ 0.33.0 && < 0.34)'.
Installing 'ExcelDna.Integration 0.33.7-rc1'.
Successfully installed 'ExcelDna.Integration 0.33.7-rc1'.
Installing 'ExcelDna.AddIn 0.33.7-rc1'.
Successfully installed 'ExcelDna.AddIn 0.33.7-rc1'.
Adding 'ExcelDna.Integration 0.33.7-rc1' to YetAnotherTestOfHardCodedPaths.
Successfully added 'ExcelDna.Integration 0.33.7-rc1' to YetAnotherTestOfHardCodedPaths.
Starting ExcelDna.Integration install script
	Set reference to ExcelDna.Integration to be CopyLocal=false
Completed ExcelDna.Integration install script
Adding 'ExcelDna.AddIn 0.33.7-rc1' to YetAnotherTestOfHardCodedPaths.
Successfully added 'ExcelDna.AddIn 0.33.7-rc1' to YetAnotherTestOfHardCodedPaths.
Starting ExcelDna.AddIn install script
	Creating -AddIn.dna file
	Adding post-build commands
	Setting startup information in Debug configuration
Completed ExcelDna.AddIn install script
```

Using Visual Studio 2013, .NET 4.5.1.

![visual-studio](https://cloud.githubusercontent.com/assets/177608/9559616/acb01bb8-4dcc-11e5-890e-817d62fc3b31.png)

**Comment by govert** [comment]
OK - I think you are checking the box that says "Create directory for Solution". I normally have that off.
This means your packages directory is under the solution and not under the project.

You might like to check it _without_ the solution directory, then the variable substitution works right.

I think the fix will be to add a check for a substitution of `$(SolutionDir)` for this case.

**Comment by CaioProiete** [comment]
@govert: You nailed it! I've just tested it without creating the directory for the solution, and it works as expected.

I agree a quick fix would be to use `$(SolutionDir)` instead of `$(ProjectDir)`.

Let me know if you plan to fix it yourself, otherwise I'll try to send a PR later today.

It is worth noticing that (by default) the `packages` folder is **always** on the same folder of `$(SolutionDir)`, so using `$(SolutionDir)` should work for both cases (creating the directory for the solution or not).

ps: We may want to revisit this eventually (low priority) for the cases where a developer changes the default place where NuGet packages are installed (by setting the `repositorypath` in a [nuget.config](https://docs.nuget.org/consume/nuget-config-file) inside `$(SolutionDir)`)

**Comment by CaioProiete** [comment]
pps: This looks like a good candidate to sneak in `v0.33` if there's still time.

**Comment by govert** [comment]
I'm not sure the packages are always under `$(SolutionDir)`. What if I add an existing project with packages to a solution, surely the packages won't move then, and `$(ProjectDir)` won't be the same a `$(SolutionDir)`.

**Comment by CaioProiete** [comment]
@govert: Correct. But that seems like a strange scenario, though, which (I suspect) would leave you in somewhat of a bad state.

i.e. Things would likely work (i.e. compile) but the next time you add a NuGet package to the newly added project, NuGet would use the `packages` folder in `$(SolutionDir)`, and the `.csproj` will have mixed `packages` folders.

But anyway, in order to support such scenario, I'm not sure what would be the best way to determine the `packages` folder that is being used by the target project where the NuGet package is being installed (to be investigated).

Anyway, I think we should move forward with `$(SolutionDir)` for now - which might not be perfect, but will work better than `$(ProjectDir)`

**Comment by govert** [comment]
I've made a basic fix for v0.33, and the rest will be part of the build targets updates for the next version.
