### ISSUE TITLE
Office 365 does not open blank workbook after startup if ExcelDNA Addin is active

### ISSUE THREAD

**Issue by korndi83** [Excel-DNA/ExcelDna#254]
Since the latest Office 365 update no empty workbook is opened on Excel startup if an ExcelDNA Addin is active.
I also removed all code from my addin class to make sure it's not my code which causes the issue.

**Comment by govert** [comment]
This is an Excel bug that affects all .xll add-ins. It was fixed in 2017, but has subsequently returned.

Please add your voice to this discussion on the "Excel for Developers" forum, to help Microsoft take note of the problem: https://social.msdn.microsoft.com/Forums/Lync/en-US/a2b1b34e-5914-48df-bc19-71fa502477d2/excel-2016-bug-the-excel-window-shows-no-content-at-startup-if-an-xll-is-registered?forum=exceldev

**Comment by govert** [comment]
@korndi83 My Excel is now updated to version 16.0.12001.20000 and the blank startup problem seems to be gone.

Could you please check with the current Excel version and confirm whether you still have this problem?

**Comment by korndi83** [comment]
Hi Govert,

I updated Excel to latest version today:
Microsoft Excel for Office 365 MSO (16.0.11328.20390) 64-Bit

But the problem still exists :(

**Comment by jimfoye** [comment]
I had a customer report this today with 16.0.11328.20438 (32 bit).

**Comment by govert** [comment]
@jimfoye Yes - that version does not seem to have the re-implementation of the fix yet. If you find versions since 16.0.12001.20000 that have the problem, I'd be interested to know.

**Comment by louwill** [comment]
Super annoying that this is still a problem in 2021.  The only suitable "fix" I've found is to disable the Excel splash screen.  I'm on 16.0.13929.20206 (32-bit).

![image](https://user-images.githubusercontent.com/1969592/118997254-884ce980-b956-11eb-8a95-bc23c8cde1a5.png)
